- name: Configure APT Sources
  ansible.builtin.template:
    src: sources.list.j2
    dest: "/etc/apt/sources.list"
    mode: "0644"

- name: Update APT Cache
  ansible.builtin.apt:
    update_cache: true

- name: Upgrade Packages
  ansible.builtin.apt:
    upgrade: true
  when: upgrade_enabled
